variables:
    GIT_LAB_REPOSITORY_URL: git.infra.cospace.de:4567/guidelines/code-quality-control/

build-docker:
  image: docker:dind
  cache: {}
  stage: deploy
  timeout: 2h
  except:
      - branches
  only:
      - /^([\d.]+).+$/
  script:
      - export BUILD_DIR=`pwd`
      - echo Test access rigths of JOB-TOKEN
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.infra.cospace.de:4567
      - docker build --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} -t ${GIT_LAB_REPOSITORY_URL}build-docker:latest .
      - docker push ${GIT_LAB_REPOSITORY_URL}build-docker:latest
      - docker build --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} -t ${GIT_LAB_REPOSITORY_URL}build-docker:$CI_COMMIT_TAG .
      - docker push ${GIT_LAB_REPOSITORY_URL}build-docker:$CI_COMMIT_TAG
      - docker rmi ${GIT_LAB_REPOSITORY_URL}build-docker:latest ${GIT_LAB_REPOSITORY_URL}build-docker:$CI_COMMIT_TAG
  tags:
      - docker
      - dind

